import type { Metadata } from "next";
import { cookies } from "next/headers";

import { ToastContainer } from "react-toastify";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientCookiesProvider } from "@/context/cookieContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();

  const token = cookieStore.get("accessToken")?.value;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientCookiesProvider token={token}>
          <ToastContainer />
          {children}
        </ClientCookiesProvider>
      </body>
    </html>
  );
}
